# Generated by Django 3.2.9 on 2021-11-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameAndSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('nameandslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.nameandslug')),
                ('age', models.IntegerField()),
            ],
            bases=('book.nameandslug',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('nameandslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.nameandslug')),
                ('pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('pubdate', models.DateField()),
                ('authors', models.ManyToManyField(to='book.Author')),
            ],
            bases=('book.nameandslug',),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('nameandslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.nameandslug')),
            ],
            bases=('book.nameandslug',),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('nameandslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.nameandslug')),
            ],
            bases=('book.nameandslug',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('nameandslug_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.nameandslug')),
                ('books', models.ManyToManyField(to='book.Book')),
            ],
            bases=('book.nameandslug',),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='book.Publisher'),
        ),
    ]
