# Generated by Django 3.2.9 on 2021-11-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211118_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
